version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8081:80'
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html
  
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
  